### ISSUE TITLE
NPE in headless environment

### ISSUE THREAD

**Issue by don-vip** [Telenav/improve-osm-plugin#3]
We have this error in JOSM unit tests

Caused by: java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.improveosm.ImproveOsmPlugin.addLayers(ImproveOsmPlugin.java:489)
	at org.openstreetmap.josm.plugins.improveosm.ImproveOsmPlugin.mapFrameInitialized(ImproveOsmPlugin.java:122)
	... 22 more
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.openstreetmap.josm.plugins.improveosm.UpdateThread$1.run(UpdateThread.java:70)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

But there's not 70 lines in UpdateThread.java. Is the source code on Github correct?

**Comment by don-vip** [comment]
this is solved now, thanks!
